import type { UserRole } from "@/lib/agui-types";

export const copy = {
  common: {
    appName: "Agente Bancário",
    send: "Enviar",
    confirm: "Confirmar",
    cancel: "Cancelar",
    close: "Fechar",
    logout: "Sair",
    retry: "Tentar novamente",
    loading: "Carregando…",
    demoBadge: "Ambiente de demonstração — dados fictícios",
  },
  login: {
    title: "Bem-vindo ao Agente Bancário",
    subtitle: "Seu assistente inteligente para limites, PIX e tarifas.",
    chooseProfile: "Escolha um perfil de demonstração",
    manualDivider: "ou entre manualmente",
    email: "E-mail",
    password: "Senha",
    enter: "Entrar",
    error: "Não foi possível entrar. Verifique suas credenciais.",
    heroTagline: "Atendimento com segurança bancária de verdade: cada operação sensível é confirmada, auditada e rastreável.",
    personaDescriptions: {
      customer: "Conta corrente, cartões e PIX",
      manager: "Carteira de clientes",
      admin: "Auditoria e conformidade",
    } satisfies Record<UserRole, string>,
  },
  roles: {
    customer: "Cliente",
    manager: "Gerente",
    admin: "Admin",
  } satisfies Record<UserRole, string>,
  chat: {
    conversations: "Conversas",
    newConversation: "Nova conversa",
    conversationFallback: "Conversa",
    emptyGreeting: "Olá",
    emptyHint: "Como posso ajudar hoje?",
    composerPlaceholder: "Digite sua mensagem",
    composerLabel: "Mensagem",
    waitingConfirmation: "Responda à confirmação acima ou cancele.",
    jumpToLatest: "Ir para a última mensagem",
    you: "Você",
    agent: "Agente",
    sources: "Fontes consultadas",
    starters: {
      customer: [
        "Qual a taxa do consignado?",
        "Qual é o meu limite?",
        "Faça um PIX de R$ 1.000",
        "Quais as tarifas da minha conta?",
      ],
      manager: [
        "Qual a taxa do consignado?",
        "Quais os limites de PIX vigentes?",
        "Como funciona a antecipação de recebíveis?",
      ],
      admin: [
        "Qual a taxa do consignado?",
        "Quais operações exigem verificação adicional?",
      ],
    } satisfies Record<UserRole, string[]>,
    toolLabels: {
      consultar_perfil: "consultando perfil",
      consultar_limite: "consultando limite",
      consultar_saldo: "consultando saldo",
      alterar_limite: "alterando limite",
      fazer_pix: "realizando PIX",
    } as Record<string, string>,
  },
  confirmation: {
    title: "Confirme a operação",
    expired: "Confirmação expirada",
    expiredHint: "Envie o pedido novamente para gerar uma nova confirmação.",
    resolved: "Operação resolvida.",
    expiresIn: (minutes: number, seconds: number) => `Expira em ${minutes} min ${seconds} s`,
    card: "Cartão",
    currentLimit: "Limite atual",
    requestedLimit: "Novo limite",
    pixAmount: "Valor",
    pixRecipient: "Destinatário",
    pixAccount: "Conta",
    operationLabels: {
      alterar_limite: "Alteração de limite",
      fazer_pix: "Transferência PIX",
    } as Record<string, string>,
  },
  stepUp: {
    title: "Verificação adicional",
    instruction: "Informe o código de 6 dígitos para continuar.",
    codeLabel: "Código",
    invalid: "Código inválido. Tente novamente.",
    attemptsLeft: (n: number) => (n === 1 ? "1 tentativa restante" : `${n} tentativas restantes`),
    cancelled: "Verificação cancelada.",
  },
  account: {
    title: "Minha conta",
    branchAccount: (agencia: string, conta: string) => `Ag. ${agencia} · C/C ${conta}`,
    balance: "Saldo disponível",
    showBalance: "Mostrar saldo",
    hideBalance: "Ocultar saldo",
    cards: "Cartões",
    limitUsed: "Limite utilizado",
    invoice: "Fatura atual",
    due: "Vencimento",
    pixLimit: "Limite PIX diário",
    transactions: "Últimas transações",
    portfolio: "Clientes da carteira",
    adminHint: "Acompanhe as operações sensíveis na Auditoria.",
    openPanel: "Abrir painel da conta",
    closePanel: "Fechar painel da conta",
    demoData: "Dados fictícios para demonstração",
  },
  admin: {
    title: "Auditoria",
    subtitle: "Eventos imutáveis de operações e decisões de segurança",
    filters: "Filtros de auditoria",
    user: "Usuário",
    action: "Ação",
    period: "Período",
    last7days: "Últimos 7 dias",
    customRange: "Intervalo personalizado",
    from: "De",
    to: "Até",
    allActions: "Todas",
    when: "Quando",
    amount: "Valor",
    outcome: "Resultado",
    empty: "Nenhum evento foi encontrado com estes filtros.",
    error: "Não foi possível carregar a auditoria.",
    loadingDetail: "Carregando detalhes…",
    detailTitle: "Detalhes do evento",
    resource: "Recurso",
    eventId: "Evento",
    details: "Detalhes",
    openTrace: "Abrir trace no Langfuse",
    traceUnavailable: "Trace não disponível para este evento.",
    previous: "Anterior",
    next: "Próxima",
    pageOf: (page: number, total: number) => `Página ${page} de ${total}`,
    securityEvent: "Evento de segurança",
    events: "Eventos de auditoria",
  },
  errors: {
    backendUnavailable: "Não foi possível falar com o banco agora.",
    boundaryTitle: "Algo deu errado",
    boundaryHint: "Recarregue a página para continuar. Se o problema persistir, informe o código abaixo.",
    reload: "Recarregar",
  },
  forbidden: {
    title: "Acesso não autorizado",
    description: "Você não tem permissão para acessar esta página.",
    backToChat: "Voltar ao chat",
    switchProfile: "Trocar de perfil",
  },
} as const;
